//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterPlaytime.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterPlaytime.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Across all characters, you have played for.
        /// </summary>
        internal static string AllCharacterMessage {
            get {
                return ResourceManager.GetString("AllCharacterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSave:.
        /// </summary>
        internal static string AutoSaveHeader {
            get {
                return ResourceManager.GetString("AutoSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current character has yet to be logged, type /playtime to update..
        /// </summary>
        internal static string CharacterNotRegistered {
            get {
                return ResourceManager.GetString("CharacterNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DisplayNormal {
            get {
                return ResourceManager.GetString("DisplayNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Option:.
        /// </summary>
        internal static string DisplayOptionHeader {
            get {
                return ResourceManager.GetString("DisplayOptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting:.
        /// </summary>
        internal static string FormattingHeader {
            get {
                return ResourceManager.GetString("FormattingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Character.
        /// </summary>
        internal static string OnCharacter {
            get {
                return ResourceManager.GetString("OnCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Output:.
        /// </summary>
        internal static string OutputHeader {
            get {
                return ResourceManager.GetString("OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute.
        /// </summary>
        internal static string PlaytimeUnderMinute {
            get {
                return ResourceManager.GetString("PlaytimeUnderMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Character:.
        /// </summary>
        internal static string SavedCharacterHeader {
            get {
                return ResourceManager.GetString("SavedCharacterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Bar:.
        /// </summary>
        internal static string ServerBarHeader {
            get {
                return ResourceManager.GetString("ServerBarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current character.
        /// </summary>
        internal static string ShowCurrentCharacter {
            get {
                return ResourceManager.GetString("ShowCurrentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show other characters.
        /// </summary>
        internal static string ShowOtherCharacter {
            get {
                return ResourceManager.GetString("ShowOtherCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string TimeDay {
            get {
                return ResourceManager.GetString("TimeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string TimeDays {
            get {
                return ResourceManager.GetString("TimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string TimeHour {
            get {
                return ResourceManager.GetString("TimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string TimeHours {
            get {
                return ResourceManager.GetString("TimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string TimeMinute {
            get {
                return ResourceManager.GetString("TimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string TimeMinutes {
            get {
                return ResourceManager.GetString("TimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string TimeSecond {
            get {
                return ResourceManager.GetString("TimeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Total:.
        /// </summary>
        internal static string TotalCharacterPlaytime {
            get {
                return ResourceManager.GetString("TotalCharacterPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string TotalPlaytime {
            get {
                return ResourceManager.GetString("TotalPlaytime", resourceCulture);
            }
        }
    }
}
